#!/usr/bin/env python
from logging import getLogger, raiseExceptions
import logging
from os import environ
import nomad
import sys
from retry import retry

my_nomad = ""
my_token = ""
isLeader = False
theHost = "https://nomad.admin.dev.wickes.systems/"

thePolicy = '''namespace "*" {
  policy       = "write"
  capabilities = ["alloc-node-exec"]
}

agent {
  policy = "write"
}

operator {
  policy = "write"
}

quota {
  policy = "write"
}

node {
  policy = "write"
}

host_volume "*" {
  policy = "write"
}
'''

def createPolicy(theToken):
    token = theToken
    logger.info("creating Policy with token",token)
    policy =  {
    "Name": "anonymous",
    "Description": "Anonymous policy",
    "Rules": thePolicy
    }

    my_nomad.acl.create_policy("anonymous", policy)

def createInstance():
  try:
    global my_nomad
    my_nomad = nomad.Nomad(host=theHost, timeout=5)
    return True
  except Exception as e:
    logger.error("the exception",e)

@retry(exceptions=Exception, tries=10, delay=5, max_delay=120, backoff=2, jitter=0)
def checkLeader():
  global my_nomad
  try:
    leader = my_nomad.status.leader.get_leader()
    logger.info("theLeader",leader)
    if (leader != ''):
      isLeader = True
      return True
  except Exception as e:
    logger.error("the exception",e)

def doBootStrap():
    global my_token
    my_token = environ.get("NOMAD_TOKEN")
    logger.info("the token from env : ",my_token)
    if (my_token == None):

      try:
          bootstrap = my_nomad.acl.generate_bootstrap()
          logger.info ("boot strap secret",bootstrap["SecretID"])
          if (bootstrap["SecretID"] != ""):
              my_token = bootstrap["SecretID"]
          else:
              my_token = ""
          
          
      except Exception as e:
          my_token = ""
          logger.error("Unexpected error:", e)
          
    environ['NOMAD_TOKEN'] = my_token 
    return my_token

    

 

global logger 
logging.basicConfig(
  format='%(asctime)s %(levelname)s %(message)s',
  filename="bootAclLog.log",
  level=logging.INFO)
logger = logging.getLogger("my_logger")
logger.info("creating instance")
 
if (createInstance()):
  if (checkLeader()):
    my_token = doBootStrap()

    if (my_token != None):
      logger.info("creating policy")
      createPolicy(my_token)
    else:
      logger.info("token is empty")
  else:
    logger.info("did not find leader")
else:
  logger.info("could not create instance")



  

